spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/woojungcard?serverTimezone=Asia/Seoul
    username: root
    password: 1234

mybatis:
  config-location: classpath:mybatis/config/config.xml
