spring:
  datasource:
    url: jdbc:mysql://localhost:3306/woojungcard?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    
  redis:
    host: localhost
    port: 6379

mybatis:
  config-location: classpath:mybatis/config/config.xml

jwt:
  ACCESS_SECRET_KEY: aidhgjarisdafjskljklriaonsdikrnsnnfkdsijkevklasdfujiielarlfnkanvdkvcxfsdgweasdv
  REFRESH_SECRET_KEY: zsxdfbnjmsdcyuhjkkrtfweecvrdftfvghfgbhmukhtgugwqesfteyhoikdwduigkwgrsdugafjixf
