spring:
  datasource:
    url: jdbc:mysql://192.168.0.31:3306/woojungcard?serverTimezone=Asia/Seoul
    username: root
    password: 1234

mybatis:
  config-location: classpath:mybatis/config/config.xml
